name: build

on: push

jobs:
  run-build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.0
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        working-directory: ./packages/molecule-ui-react
        run: yarn install
      - name: build
        working-directory: ./packages/molecule-ui-react
        run: yarn build
